### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by amiltonwong** [uzh-rpg/rpg_open_remode#15]
Dear all,

I had downloaded the remode package and built it successfully. (Without ROS)

Now , after I download the test dataset, and run the command as guided from wiki,
https://github.com/uzh-rpg/rpg_open_remode/wiki/Test-REMODE

I came across the run error.
The details are listed here:
https://gist.github.com/amiltonwong/8950c9e2dcb685840717

My system is Ubtuntu 14.04, titan GPU, CUDA version: 7.5.

Any suggestions to fix this issue?

Thanks in advance~
Milton

**Comment by amiltonwong** [comment]
Also , when executing command:
 ./dataset_main

I came across read dataset error
root@milton-OptiPlex-9010:~/remode-ws/rpg_open_remode/bin# ./dataset_main 
Running executable: ./dataset_main
Checking available CUDA-capable devices...
1 CUDA-capable GPU detected:
Device 0 - GeForce GTX TITAN
Using GPU device 0: "GeForce GTX TITAN" with compute capability 3.5
GPU device 0 has 14 Multi-Processors, SM 3.5 compute capabilities

ERROR: could not read dataset

**Comment by pizzoli** [comment]
Hi Milton,
thanks for your interest.
It seems that the test executables cannot access the test data.
Did you set the path to the downloaded test data in the environment variable?
The command line should look like this:
export RMD_TEST_DATA_PATH=$MY_WORKSPACE/rpg_open_remode/test_data
Please adapt it to the folder where you have saved the test data.

**Comment by amiltonwong** [comment]
Thanks @pizzoli ,
You're right, I solve it by linking it to the test_data folder.
