### ISSUE TITLE
Depth estimation

### ISSUE THREAD

**Issue by melights** [uzh-rpg/rpg_open_remode#18]
Hi @Pizzoli,

Your work is very impressive!

I would like to use other pose estimation method to pass the camera pose and location to you remode. However, I noticed that except from the pose and location, the message from SVO also pass the depth map to remode. And remode create a reference map based on the max and min depth. Can you please let me know how to set these values if I cannot estimate a initial depth from other pose estimation method.

Looking forward to your kind reply.

**Comment by pizzoli** [comment]
Hi,
thank you for your interest. 
The max and min depth parameters should be set according to your prior knowledge of the scene.

**Comment by imhzxuan** [comment]
Hi @pizzoli @melights ,

I also found that depth maps are passed from SVO to REMODE. I'm little confused about what the function of these maps are. Are they just generated to get the max and min depth? And if depth maps has already been generated, what's the meaning of REMODE? Really appreciate it if you can explain something about them.

Thanks!
