### ISSUE TITLE
CudaException: Unable to bind texture

### ISSUE THREAD

**Issue by Thunderbolt-sx** [uzh-rpg/rpg_open_remode#3]
I have successfully built the program, but when I run "dataset_main" it terminate with following error:
terminate called after thjrowing an instance of 'rmd::CudaException' 
  what(): CudaException: Unable to bind texture:
cudaError code: invalid texture reference (18)

In addition, "all_test" only pass for first test, it failed on the others for for similar reason as above. My system is Ubuntu 14.04 with Cuda 7.0 (GTX980)

Thanks for any advice!

**Comment by pizzoli** [comment]
Hi, thanks for testing it. My guess is that it has to deal with the compute capability.
It is specified in the CMakeLists.txt file, as an NVCC flag: -gencode arch=compute_30,code=sm_30;
Can you try to set it to 35 or higher?

**Comment by Thunderbolt-sx** [comment]
Thanks for your reply. I have tested with 32(which I used for other project) and 35. But all result in same error as before.

**Comment by pizzoli** [comment]
I'm trying to replicate it but I don't have a maxwell architecture yet. I removed platform specific flags from the CMakeLists.txt file, can you try to build it again? Please remove the build folder first.

**Comment by Thunderbolt-sx** [comment]
After removing specific flags, dataset_main works, but all_test failed at seed_matrix_test with following error message "Value of: cu_converge.at<int>(r,c) Actual: 5 Expected: rmd::ConvergenceStates::UPDATE which is: 0, (r, c) = (5, 5)"

Thank you for your solution :D
