### ISSUE TITLE
How can I use video frames from webcam instead of sample images?

### ISSUE THREAD

**Issue by Sanghoon94** [uzh-rpg/rpg_open_remode#4]
Hello, I am Sanghoon Kang.

I am trying to use video from my webcam (live / pre-recorded both are okay).

How can I use webcam instead of sample datasets?

Thank you.

**Comment by pizzoli** [comment]
Dear Sanghoon Kang,
thank you for your interest.
Please note that issues are for notifying about errors or bugs. You should do not open issues for discussing possible features or requesting help. You might open an issue, for instance, if you feel like the documentation is lacking some information.

Concerning your question, you need to provide Open REMODE with images and related camera poses.
You can learn everything you need to know by looking at the tests and at the execution on the dataset.
For camera pose estimation, there is a plethora of approaches available. You might start having a look at this project:
https://github.com/uzh-rpg/rpg_svo
I hope this helps. 
Regards

**Comment by pizzoli** [comment]
Hi,
this is just to let you know that I added a simple ROS node.
You can run SVO and REMODE on the live stream of your calibrated camera.
Have fun!

2015-10-13 7:44 GMT+02:00 Sanghoon94 <notifications@github.com>:

> Hello, I am Sanghoon Kang.
>
> I am trying to use video from my webcam (live / pre-recorded both are
> okay).
>
> How can I use webcam instead of sample datasets?
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uzh-rpg/rpg_open_remode/issues/4>.
>



-- 
Matia Pizzoli
